### ISSUE TITLE
HTTP 500 should reject promise

### ISSUE THREAD

**Issue by GeoffreyPlitt** [therootcompany/request.js#15]
I'm doing `await request.get('https://the-internet.herokuapp.com/status_codes/500')`

Based on https://github.com/request/request-promise, I expect 4xx and 5xx status codes to reject that promise being awaited.

But they're not.

Is there a way to get this kind of behavior?

**Comment by coolaj86** [comment]
That actually _shouldn't_ be rejected because the _HTTP Request_ was successful and the _HTTP Response_ was also successful (there was no network or byte sequence error), but the HTTP Response _contained_ an error message for the application to figure out what to do with (i.e. the error message might be JSON).

I'm pretty sure that's how the original `request` worked but, even if I'm mistaken, I can't "fix" this library because it would unexpectedly break things downstream in other libraries.

There is a property `ok`, which you can check: \
(the original `request` doesn't have that, I copied it from the `fetch` API)

```js
let resp = request.get('https://the-internet.herokuapp.com/status_codes/500');
if (!resp.ok) {
  throw new Error(`got status code ${resp.status}`);
}
```

However, I'd also say that now is a good time to switch over to `fetch`. It's been natively supported since v17 and the API is now marked as stable.

I still use this library for compatibility with older projects, but I don't use it with new projects.

**Comment by GeoffreyPlitt** [comment]
Oh darn. I thought this had some functionality similar to https://www.npmjs.com/package/request-promise, my mistake. Thanks.
